# This workflow builds with Gradle, publishes to GitHub Packages, and deploys Maven artifacts and documentation to GitHub Pages

name: Gradle Package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish to GitHub Packages
        run: ./gradlew publish
        continue-on-error: true
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSILITE_USER: ${{ secrets.REPOSILITE_USER }}
          REPOSILITE_PASSWORD: ${{ secrets.REPOSILITE_PASSWORD }}

      - name: Generate Maven repository for GitHub Pages
        run: ./gradlew publishToPages copyMavenToPages

      - name: Generate Javadoc
        run: ./gradlew javadoc

      - name: Create GitHub Pages directory structure
        run: |
          mkdir -p gh-pages-content
          # Copy Maven repository to root of gh-pages
          cp -r maven-repo/* gh-pages-content/
          # Copy Javadoc to docs/ subdirectory
          mkdir -p gh-pages-content/docs
          cp -r build/docs/javadoc/* gh-pages-content/docs/
          # Create index.html for easier navigation
          cat > gh-pages-content/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
            <title>Trailblazer - Maven Repository and Documentation</title>
            <style>
              body { font-family: Arial, sans-serif; margin: 40px; }
              .container { max-width: 800px; }
              .card { border: 1px solid #ddd; border-radius: 8px; padding: 20px; margin: 20px 0; }
              .card h2 { margin-top: 0; color: #333; }
              .card a { color: #0066cc; text-decoration: none; }
              .card a:hover { text-decoration: underline; }
            </style>
          </head>
          <body>
            <div class="container">
              <h1>🚀 Trailblazer</h1>
              <p>Welcome to the Trailblazer Maven repository and documentation site.</p>
              
              <div class="card">
                <h2>📚 API Documentation</h2>
                <p>Browse the latest Javadoc documentation for the Trailblazer library.</p>
                <a href="docs/">View Documentation →</a>
              </div>
              
              <div class="card">
                <h2>📦 Maven Repository</h2>
                <p>Maven artifacts are available in this repository. Add this repository to your project:</p>
                <pre><code>&lt;repository&gt;
            &lt;id&gt;trailblazer-gh-pages&lt;/id&gt;
            &lt;url&gt;https://alphagamedeveloper.github.io/Trailblazer/&lt;/url&gt;
          &lt;/repository&gt;</code></pre>
                <a href="dev/">Browse Repository →</a>
              </div>
            </div>
          </body>
          </html>
          EOF

      - name: Upload GitHub Pages content
        uses: actions/upload-artifact@v4
        with:
          name: gh-pages-content
          path: gh-pages-content

  deploy-pages:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Download GitHub Pages content
        uses: actions/download-artifact@v4
        with:
          name: gh-pages-content
          path: gh-pages-content

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages-content
          publish_branch: gh-pages
          force_orphan: true
          commit_message: "Deploy Maven repository and documentation for release"