name: Upload Snapshot Release
on:
    push:
    workflow_dispatch:
    

jobs:
    upload-snapshot:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4

        - name: Set up JDK 17
          uses: actions/setup-java@v4
          with:
            java-version: '17'
            distribution: 'temurin'
            server-id: github
            settings-path: ${{ github.workspace }}

        - name: Setup Gradle
          uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

        - name: Get latest tag
          uses: actions-ecosystem/action-get-latest-tag@v1
          id: get-latest-tag
          
        - name: Build with Gradle
          run: ./gradlew build
          env:
            GIT_TAG: ${{ steps.get-latest-tag.outputs.tag }}
            SNAPSHOT: true

        - name: Generate and copy snapshot Javadoc
          run: ./gradlew copySnapshotJavadoc
          env:
            GIT_TAG: ${{ steps.get-latest-tag.outputs.tag }}
            SNAPSHOT: true

        - name: Upload Snapshot Javadoc
          uses: actions/upload-artifact@v4
          with:
            name: snapshot-javadoc
            path: build/docs/javadoc/SNAPSHOT

        - name: Publish snapshot to maven.alphagame.dev
          run: ./gradlew publishSnapshotToReposilite
          env:
            USERNAME: ${{ github.actor }}
            TOKEN: ${{ secrets.GITHUB_TOKEN }}
            REPOSILITE_USER: ${{ secrets.REPOSILITE_USER }}
            REPOSILITE_PASSWORD: ${{ secrets.REPOSILITE_PASSWORD }}
            GIT_TAG: ${{ steps.get-latest-tag.outputs.tag }}
            SNAPSHOT: true

    deploy-snapshot-docs:
        needs: upload-snapshot
        runs-on: ubuntu-latest
        permissions:
          contents: write # Needed for GitHub Pages deployment
          
        steps:
        - uses: actions/checkout@v4
        
        - name: Download Snapshot Javadoc
          uses: actions/download-artifact@v4
          with:
            name: snapshot-javadoc
            path: javadoc/SNAPSHOT
            
        - name: Deploy Snapshot Javadoc to GitHub Pages
          uses: peaceiris/actions-gh-pages@v4
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./javadoc
            publish_branch: gh-pages
            keep_files: true